### ISSUE TITLE
Out-of-date MongoDB Shell

### ISSUE THREAD

**Issue by adaminspace** [cloudacademy/cosmos-db-lab-artifacts#1]
The version of MongoDB Shell in this repo does not work with the current Azure Cloud Shell, so the lab **Working with Azure Cosmos DB - Working with the Cosmos DB MongoDB API** cannot be completed using the current instructions. This repo needs to be updated with the latest version of the MongoDB Shell available from MongoDB: https://fastdl.mongodb.org/linux/mongodb-shell-linux-x86_64-debian10-4.4.3.tgz

**Comment by lrakai** [comment]
Thanks for reporting the issue and the proposed fix!  I have updated the mongo client and also some deprecated commands in the lab.
